logging:
  level:
    org.springframework: DEBUG

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
          - mappings
          - scheduledtasks
          - env
          - refresh
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    env:
      enabled: true
    prometheus:
      enabled: true
    mappings:
      enabled: true
    scheduledtasks:
      enabled: true
    refresh:
      enabled: true

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  config:
    import: "configtree:${SECRETS_BASE_PATH:}/app/config/secrets/"